// AUTO-GENERATED by thicken-reports/_i18n_p10_blog_resume.py — do not hand-edit.
import type { Lang } from './config'
import type { BlogFullArticle } from './blogFull'
import { getBlogFull } from './blogFull'

import ai_agent_token_cost_attribution_2026__en from './blog-full/ai-agent-token-cost-attribution-2026.en.json'
import ai_agent_token_cost_attribution_2026__da from './blog-full/ai-agent-token-cost-attribution-2026.da.json'
import ai_agent_token_cost_attribution_2026__de from './blog-full/ai-agent-token-cost-attribution-2026.de.json'
import ai_agent_token_cost_attribution_2026__es from './blog-full/ai-agent-token-cost-attribution-2026.es.json'
import ai_agent_token_cost_attribution_2026__fr from './blog-full/ai-agent-token-cost-attribution-2026.fr.json'
import ai_agent_token_cost_attribution_2026__it from './blog-full/ai-agent-token-cost-attribution-2026.it.json'
import ai_agent_token_cost_attribution_2026__nl from './blog-full/ai-agent-token-cost-attribution-2026.nl.json'
import ai_agent_token_cost_attribution_2026__pt_BR from './blog-full/ai-agent-token-cost-attribution-2026.pt-BR.json'
import ai_agent_token_cost_attribution_2026__pt_PT from './blog-full/ai-agent-token-cost-attribution-2026.pt-PT.json'
import ai_agent_token_cost_attribution_2026__zh from './blog-full/ai-agent-token-cost-attribution-2026.zh.json'
import finops_budget_guardrails_for_llm_agents_2026__en from './blog-full/finops-budget-guardrails-for-llm-agents-2026.en.json'
import finops_budget_guardrails_for_llm_agents_2026__da from './blog-full/finops-budget-guardrails-for-llm-agents-2026.da.json'
import finops_budget_guardrails_for_llm_agents_2026__de from './blog-full/finops-budget-guardrails-for-llm-agents-2026.de.json'
import finops_budget_guardrails_for_llm_agents_2026__es from './blog-full/finops-budget-guardrails-for-llm-agents-2026.es.json'
import finops_budget_guardrails_for_llm_agents_2026__fr from './blog-full/finops-budget-guardrails-for-llm-agents-2026.fr.json'
import finops_budget_guardrails_for_llm_agents_2026__it from './blog-full/finops-budget-guardrails-for-llm-agents-2026.it.json'
import finops_budget_guardrails_for_llm_agents_2026__nl from './blog-full/finops-budget-guardrails-for-llm-agents-2026.nl.json'
import finops_budget_guardrails_for_llm_agents_2026__pt_BR from './blog-full/finops-budget-guardrails-for-llm-agents-2026.pt-BR.json'
import finops_budget_guardrails_for_llm_agents_2026__pt_PT from './blog-full/finops-budget-guardrails-for-llm-agents-2026.pt-PT.json'
import finops_budget_guardrails_for_llm_agents_2026__zh from './blog-full/finops-budget-guardrails-for-llm-agents-2026.zh.json'

const CATALOG: Record<string, Partial<Record<Lang, BlogFullArticle>>> = {
  'ai-agent-token-cost-attribution-2026': {
    'en': ai_agent_token_cost_attribution_2026__en as BlogFullArticle,
    'da': ai_agent_token_cost_attribution_2026__da as BlogFullArticle,
    'de': ai_agent_token_cost_attribution_2026__de as BlogFullArticle,
    'es': ai_agent_token_cost_attribution_2026__es as BlogFullArticle,
    'fr': ai_agent_token_cost_attribution_2026__fr as BlogFullArticle,
    'it': ai_agent_token_cost_attribution_2026__it as BlogFullArticle,
    'nl': ai_agent_token_cost_attribution_2026__nl as BlogFullArticle,
    'pt-BR': ai_agent_token_cost_attribution_2026__pt_BR as BlogFullArticle,
    'pt-PT': ai_agent_token_cost_attribution_2026__pt_PT as BlogFullArticle,
    'zh': ai_agent_token_cost_attribution_2026__zh as BlogFullArticle,
  },
  'finops-budget-guardrails-for-llm-agents-2026': {
    'en': finops_budget_guardrails_for_llm_agents_2026__en as BlogFullArticle,
    'da': finops_budget_guardrails_for_llm_agents_2026__da as BlogFullArticle,
    'de': finops_budget_guardrails_for_llm_agents_2026__de as BlogFullArticle,
    'es': finops_budget_guardrails_for_llm_agents_2026__es as BlogFullArticle,
    'fr': finops_budget_guardrails_for_llm_agents_2026__fr as BlogFullArticle,
    'it': finops_budget_guardrails_for_llm_agents_2026__it as BlogFullArticle,
    'nl': finops_budget_guardrails_for_llm_agents_2026__nl as BlogFullArticle,
    'pt-BR': finops_budget_guardrails_for_llm_agents_2026__pt_BR as BlogFullArticle,
    'pt-PT': finops_budget_guardrails_for_llm_agents_2026__pt_PT as BlogFullArticle,
    'zh': finops_budget_guardrails_for_llm_agents_2026__zh as BlogFullArticle,
  },
}

export const BLOG_FULL_SLUGS = Object.keys(CATALOG)

export function loadBlogFull(slug: string, locale: Lang): BlogFullArticle | null {
  return getBlogFull(CATALOG, slug, locale)
}

